# Configure the Vagrant daemon to utilize Centos7 image #
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  config.vm.network "forwarded_port", guest: 3389, host: 42069

  # Install needed Software #
  config.vm.provision "shell", inline: <<-SHELL
    rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm # Add epel repo #
    yum -y install xrdp tigervnc-server # Install the RDP-Server and the daemon for it #
    yum -y install lightdm # install DM #
    yum -y install openbox # install WM #
    yum -y install terminator # install a terminal emulator #    
    yum -y install nautilus # install filemanager #
    yum -y install firefox # install web browser #
    yum -y install google-droid-sans-mono-fonts # install monospace fonts #

    systemctl enable xrdp # allow xrdp to start on login #

    firewall-cmd --permanent --add-port=3389/tcp # Allow XRDP through the firewall #
    firewall-cmd --reload # reload the firewall #

    useradd user; echo -e "al-Lad71\nal-Lad71" | passwd user # Create user and set new password #
    echo "user ALL=(ALL) ALL" >> /etc/sudoers # add user to sudoers list #

    cd /home/user
    ls -al
    echo "openbox-session" > .xsession #set xsession session type #
    chmod +x .xsession # make .xsession executable #
    ls -al

    echo -e "al-Lad71" | su -l user # login as user #
    echo -e "al-Lad71" | sudo mkdir ~/.config # create config folder for nautilus #
    echo -e "al-Lad71" | sudo mkdir ~/.config/nautilus # create nautilus preferences folder #
    echo -e "al-Lad71" | sudo systemctl start xrdp # Start xrdp #
    echo -e "al-Lad71" | sudo systemctl isolate graphical.target # Start a user session #
   SHELL
end
